### ISSUE TITLE
Result Bars missing from Korean Dictionary

### ISSUE THREAD

**Issue by JarrodCTaylor** [LuminareMed/quickscreen-translations#19]
Would be nice to get the button text as well
<img width="1507" alt="image" src="https://user-images.githubusercontent.com/4416952/78190595-ef999880-7439-11ea-910a-7beb8f09d1d7.png">

**Comment by oakmac** [comment]
FYI @semper21 - we have a handful of "high value" Korean translations if you have any bandwidth to help out. The two highest value are probably these:

```edn
 :result-bar/click-to-proceed "Click to Proceed with Screen"
 :result-bar/please-complete-all-fields "Please complete all fields"
```

But anything with a `FIXME` comment in `dictionaries/ko.edn` is fair game :)

Resource ids below line 200 are likely to be removed from the product soon; not a high priority.

**Comment by semper21** [comment]
@oakmac I've translated more texts - please see #21. In order to complete translation, I have a couple questions/comments:
-Can I get some context for lines 6 and 11?
-Lines 27-28, and 54, 55 may need to be updated to use positional arguments

(Disclaimer: I am not an official translator. In the beginning I was told to leave untranslated texts as-is because the language may have needed to be officially sourced, which is why I've been apprehensive about making my own translations. I tried my best, and hope this helps!)

**Comment by oakmac** [comment]
> I was told to leave untranslated texts as-is because the language may have needed to be officially sourced, which is why I've been apprehensive about making my own translations.

Yes - this is important mainly for the numbered screening questions and answers where the translation document came from Harris County / City of Houston directly. For the rest of the application that requirement is less strict.

Also we have been signing up additional counties who are not able to provide translations. In that case we just go with what Harris provided.

>  I tried my best, and hope this helps!

Your contributions have been huge and greatly appreciated. We spoke with the Harris call center earlier this week who mentioned that the Houston Korean community has been very engaged with the screening tool largely as a result of the translation (ie: your work!)

**Comment by oakmac** [comment]
> context for line 6

It is in the header. "From Luminare"

![Screenshot_2020-04-02_11-04-35](https://user-images.githubusercontent.com/98485/78271427-c1679780-74d1-11ea-9fcc-9e5e004c6e5f.png)

> context for line 11

Button in the footer. Not currently being used.

![Screenshot_2020-04-02_11-05-46](https://user-images.githubusercontent.com/98485/78271610-fa077100-74d1-11ea-9ebc-eeb8070cfc9f.png)

**Comment by oakmac** [comment]
> Lines 27-28, and 54, 55 may need to be updated to use positional arguments

Yup - agree. We can work on that downstream.

FYI @gauraklein

**Comment by semper21** [comment]
@oakmac speaking of translation from Harris County/City of Houston... line 145 has been bothering me for awhile. I feel like their translation is too literal - it says "I feel nauseous" instead of general "feeling unwell." Can I change it?

**Comment by oakmac** [comment]
> line 145 has been bothering me for awhile. I feel like their translation is too literal - it says "I feel nauseous" instead of general "feeling unwell." Can I change it?

Yes

**Comment by gauraklein** [comment]
> > Lines 27-28, and 54, 55 may need to be updated to use positional arguments
> 
> 
> 
> Yup - agree. We can work on that downstream.
> 
> 
> 
> FYI @gauraklein

Can do that this afternoon

**Comment by aarandela** [comment]
This has been resolved! Thanks again @semper21 🙏🤙
