### ISSUE TITLE
Mandarin Chinese translation

### ISSUE THREAD

**Issue by kexiZeroing** [LuminareMed/quickscreen-translations#3]
Hi,
I can help to add the Chinese dictionary based on the `en.edn` and `Mods_ZH.pdf`. I want to make sure what I need to do is just 1) fork and clone this repo; 2) add the `zh.edn` file to a new branch; 3) open a pull request, and you will handle the rest. Is that correct?

I will do this when you reply to me and complete it today :)

**Comment by oakmac** [comment]
> I want to make sure what I need to do is just 1) fork and clone this repo; 2) add the zh.edn file to a new branch; 3) open a pull request, and you will handle the rest. Is that correct?

Yes - exactly :)

> I will do this when you reply to me and complete it today :)

Amazing!

You may want to take a look here, I believe @LannyWang009 has already done some work for ZH: https://github.com/LannyWang009/quickscreen-translations But there is not a PR open yet.

**Comment by kexiZeroing** [comment]
Thanks. I will contact @LannyWang009 and complete it.

**Comment by kexiZeroing** [comment]
@oakmac, LannyWang009 have made a PR. Could you merge that and I can translate the rest part?

**Comment by adamfeldman** [comment]
@kexiZeroing FYI @oakmac merged #4 (just in-case you didn't already see 🙂)

**Comment by aarandela** [comment]
Love this community! Thanks for all the work! Closing issue
