### ISSUE TITLE
Korean translation

### ISSUE THREAD

**Issue by adamfeldman** [LuminareMed/quickscreen-translations#8]
(I made a [r/Houston](https://www.reddit.com/r/houston/comments/fq3mkd/translators_needed_for_checkforcoronacom_harris/) post to recruit translators)

A friendly Korean native speaker is currently working on matching up the Korean strings from the Word doc to the EDN keys, using the tool described in #1.

**Comment by oakmac** [comment]
PR #9 has been merged. Very cool - thank you for the assist @adamfeldman !
